
struct Precipitation {
    float               precipIntensity;
    float               precipIntensityError;
    float               precipProbability;
    string              precipType;
    float               precipAccumulation;
    float               precipIntensityMax;
};

struct Atmospheric {
    float               cloudCover;
    float               dewPoint;
    float               humidity;
    float               ozone;
    float               pressure;
    float               uvIndex;
    unsigned long long  uvIndexTime;
    float               visibility;
    float               windBearing;
    float               windGust;
    unsigned long long  windGustTime;
    float               windSpeed;
};

struct WeatherCondition {
    float               apparentTemperature;
    string              icon;
    string              summary;
    float               temperature;
    unsigned long long  time;
    Precipitation       precipitationData;
    Atmospheric         atmosphericData;
};

struct DailyWeather {
    float               apparentTemperature;
    float               apparentTemperatureHigh;
    unsigned long long  apparentTemperatureHighTime;
    float               apparentTemperatureLow;
    unsigned long long  apparentTemperatureLowTime;
    Precipitation       precipitationData;
    Atmospheric         atmosphericData;
    string              icon;
    string              summary;
    float               moonPhase;
    unsigned long long  sunriseTime;
    unsigned long long  sunsetTime;
    float               temperature;
    float               temperatureHigh;
    unsigned long long  temperatureHighTime;
    float               temperatureLow;
    unsigned long long  temperatureLowTime;
    unsigned long long  time;
};

struct WeatherForcast {
    string                 summary;
    string                 icon;
    sequence<DailyWeather> forcast;
};

struct WeatherAlert {

};
